#!/usr/bin/env python

import rospy
from nclt2rosbag.initializer import Initializer


def main():

    rospy.init_node('nclt2rosbag')

    init = Initializer()

    rospy.spin()


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
