#!/usr/bin/env python

import rospy
from nclt2ros.downloader.download import Download
from nclt2ros.extractor.extract import Extract
from definitions import ROOT_DIR


def main():

    rospy.init_node('nclt2downloader')
    rospy.loginfo("running node 'nclt2downloader'")

    date = rospy.get_param('~date', '2013-01-10')

    RAW_DATA_PATH_DFLT = ROOT_DIR + '/nclt2ros/raw_data/'
    raw_data_path = rospy.get_param('~raw_data_path', RAW_DATA_PATH_DFLT)

    lb3    = rospy.get_param('~lb3',    False)
    sen    = rospy.get_param('~sen',    False)
    vel    = rospy.get_param('~vel',    False)
    hokuyo = rospy.get_param('~hokuyo', False)
    gt     = rospy.get_param('~gt',     False)
    gt_cov = rospy.get_param('~gt_cov', False)

    loader = Download(date=date, raw_data_path=raw_data_path, lb3=lb3, sen=sen, vel=vel, hokuyo=hokuyo, gt=gt, gt_cov=gt_cov)

    extractor = Extract(date=date, lb3=lb3, sen=sen, vel=vel, hokuyo=hokuyo)

    rospy.loginfo("terminating node 'nclt2downloader'")


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
