#!/usr/bin/env python

import rospy
from definitions import ROOT_DIR


def main():

    rospy.init_node('nclt2visualize')

    date = rospy.get_param('~date', '2013-01-10')

    DEFAULT_PATH = ROOT_DIR + '/raw_data/'

    rospy.spin()


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass